CREATE TABLE IF NOT EXISTS SF_BIDM_WORK_PRD.SF_SB_PRED_DEV.DBT_LOGGING (
    id BIGINT AUTOINCREMENT,
    dbt_run_id: STRING,
    log_timestamp TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP,
    log_level INT,
    model_name STRING,
    schema_name STRING,
    environment STRING,
    message STRING,
    data_preview OBJECT
);

ALTER TABLE SF_BIDM_WORK_PRD.SF_SB_PRED_DEV.DBT_LOGGING ADD PRIMARY KEY (id);
ALTER TABLE SF_BIDM_WORK_PRD.SF_SB_PRED_DEV.DBT_LOGGING ADD CONSTRAINT log_level_check CHECK (log_level IN (0, 1, 2, 3));
ALTER TABLE SF_BIDM_WORK_PRD.SF_SB_PRED_DEV.DBT_LOGGING ADD CONSTRAINT model_name_not_null CHECK (model_name IS NOT NULL);
